#!/bin/sh

echo "Running autopep8..."
autopep8 --in-place --recursive coding-agent webhook-service reviewer-agent shared
git add -u

echo "Running pylint..."
pylint coding-agent webhook-service reviewer-agent shared || exit 1

echo "Running pytest..."
#pytest || exit 1