#!/bin/sh

echo "Running autopep8..."
autopep8 --in-place --recursive coding-agent indexer-service webhook-service reviewer-agent shared
git add -u

echo "Running pylint..."
pylint coding-agent indexer-service webhook-service reviewer-agent || exit 1

echo "Running pytest..."
pytest || exit 1